import { GlobalMessageTypes } from "@Types/globals";

const GlobalMessage: GlobalMessageTypes = {
	ERROR: {
		MOBILE_NOT_VERIIED: "mobile not verified.",
		UNAUTHORIZED: "Unauthorized user access",
		USER_NOT_FOUND: "User not Found.",
		INVALID_EMAIL: "Email Not Received.",
		INVALID_PASSWORD: "Password Not Received.",
		INCORRECT_PASSWORD: "You have Entered Wrong Password.",
		AUTH_TOKEN_NOT_RECEIVED: "Login token not received.",
		INVALID_TOKEN: "Supplied login token is invalid.",
		FNAME_NOT_FOUND: "First name not received.",
		LNAME_NOT_FOUND: "Last name not received.",
		REGISTERED_NOT_FOUND: "Registered from not received.",
		REGISTERED_DEVICE_NOT_FOUND: "Registration device not received.",
		USER_ALREADY_REGISTERED: "This email is already registered with us.",
		EMAIL_NOT_VERIFIED: "Email not verified.",
		SUBJECT_NOT_FOUND: "Subject Id not Received",
		DATA_NOT_FOUND: "Data Not Found.",
		DOB_NOT_FOUND: "DOB not received.",
		PHONE_NOT_FOUND: "Phone number not received.",
		PHONE_EXIST: "Phone number already exist.",
		CLASS_ID_NOT_FOUND: "Class Id not receviced.",
		SUB_ID_NOT_FOUND: "Subject Id not received.",
		CURRENT_PWD_NOT_FOUND: "Current Password not received.",
		NEW_PWD_NOT_FOUND: "New Password not received.",
		CURRENT_PWD_INCORECT: "Incorrect current password.",
		SAME_PASSWORD: "You have entered same current and new password.",
		OFFICIALEMAILID_IS_NOT_DIFFERENT_FROM_EMAILID: "Official EmailId should be different from EmailId"
	},
	SUCCESS: {
		LOGIN_SUCCESS: "Login Successfully.",
		PASSWORD_CHANGED: "Password changed successfully.",
		USER_REGISTERED: "User Registered Successfully",
		EMAIL_SENT: "Email sent to user.",
		USER_UPDATED: "User details updated.",
	},
	SUCCESS_TYPE: {
		USER_NOT_FOUND: "USER_NOT_FOUND",
		INVALID_EMAIL: "INVALID_EMAIL",
		INVALID_PASSWORD: "INVALID_PASSWORD",
		INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
		AUTH_TOKEN_NOT_RECEIVED: "AUTH_TOKEN_NOT_RECEIVED",
		INVALID_TOKEN: "INVALID_TOKEN",
		PASSWORD_CHANGED: "PASSWORD_CHANGED",
		FNAME_NOT_FOUND: "FNAME_NOT_FOUND",
		LNAME_NOT_FOUND: "LNAME_NOT_FOUND",
		EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
		PASSWORD_NOT_FOUND: "PASSWORD_NOT_FOUND",
		REGISTERED_NOT_FOUND: "REGISTERED_NOT_FOUND",
		REGISTERED_DEVICE_NOT_FOUND: "REGISTERED_DEVICE_NOT_FOUND",
		USER_ALREADY_REGISTERED: "USER_ALREADY_REGISTERED",
		USER_REGISTERED: "USER_REGISTERED",
		EMAIL_SENT: "EMAIL_SENT",
		SUBJECT_NOT_FOUND: "SUBJECT_NOT_FOUND",
		DATA_NOT_FOUND: "DATA_NOT_FOUND",
		DOB_NOT_FOUND: "DOB_NOT_FOUND",
		PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
		USER_UPDATED: "USER_UPDATED",
		PHONE_EXIST: "PHONE_EXIST",
		CLASS_ID_MISSING: "CLASS_ID_MISSING",
		SUB_ID_NOT_FOUND: "SUBJECT_ID_NOT_FOUND",
		PASSWORD_NOT_MATCHED: "PASSWORD_NOT_MATCHED",
		SAME_PASSWORD: "SAME_PASSWORD",
		EMAIL_NOT_VERIFIED : "EMAIL_NOT_VERIFIED",
		OFFICIALEMAILID_IS_NOT_DIFFERENT_FROM_EMAILID: "Official EmailId should be different from EmailId"
	}
};

module.exports = GlobalMessage;